"""Strict, read-only consumer for the platform-steward v1 audit projection.

The canonical contracts live in ``masonjames/platform-infra``.  This module
does not project Chronicle records, write storage, call a network, or grant
authority.  It validates and normalizes a precomputed public audit projection
whose exact source revision and generated bytes are pinned in this repository.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from collections.abc import Callable, Mapping
from datetime import datetime
from pathlib import Path
from typing import TypeAlias, cast

API_VERSION = "platform.masonjames.dev/steward/v1"
AUDIT_VECTOR_KIND = "PlatformStewardAuditProjectionRecords"
HASH_ALGORITHM = "domain-separated-canonical-json-sha256-v1"
RECORD_HASH_DOMAIN = b"platform-steward-record-v1\x00"
PINNED_CANONICAL_COMMIT = "c02dbcdfacc6421c10eb863016d8aff346cef436"
PINNED_GENERATOR_SHA256 = "sha256:6ea228e5331dec4fb72be2fc077a940928291f230955103cb20eea33652c82d4"
PINNED_SCHEMA_MANIFEST_SHA256 = "sha256:d685f2fd4af55f7222f3c1205b55c4bf7c20c85d0cb3038a29fa0adf5b3211ee"
PINNED_AUDIT_VECTOR_SHA256 = "sha256:9866294256dd497d31a696a58f0db854a05064a6cb4f007b93a9f36f7236223e"
PINNED_CANONICAL_HASH_VECTOR_SHA256 = "sha256:4525bc33203e926e2dbe8aa6319be1d33a55c36c151573a522d7f3238370e603"

JSON_SAFE_INTEGER_MAX = 9_007_199_254_740_991
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
IDENTIFIER_RE = re.compile(r"^[a-z0-9][a-z0-9._:/-]*$")
UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
UTC_TIMESTAMP_RE = re.compile(
    r"^[0-9]{4}-(0[1-9]|1[0-2])-([0-2][0-9]|3[01])T"
    r"([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]Z$"
)
SOURCE_REVISION_RE = re.compile(r"^[0-9a-f]{40}$")

CLAIM_SUPPORT_STATES = (
    "supported",
    "stale",
    "conflicted",
    "revoked",
    "unsupported",
    "superseded",
)
WARNING_CATEGORIES = ("stale", "conflicted", "revoked", "unsupported", "pending")
FOUNDRY_DENIED_CAPABILITIES = (
    "bash",
    "ssh",
    "onepassword",
    "docker-socket",
    "provider-credentials",
    "production-mcp",
    "external-write",
)
FOUNDRY_ISOLATION_CHECK_NAMES = (
    "bind-admission-controller",
    "bind-dependency-lock",
    "bind-fixture-bundle",
    "bind-image-digest",
    "bind-immutable-input-output-channel",
    "bind-license-inventory",
    "bind-network-policy",
    "bind-one-job-destruction-policy",
    "bind-runtime-profile",
    "bind-sbom",
    "bind-source-archive",
    "bind-source-provenance",
    "deny-bash-child-process",
    "deny-browser-half",
    "deny-devices",
    "deny-docker-socket",
    "deny-external-write",
    "deny-host-mounts",
    "deny-host-network-pid-ipc",
    "deny-host-sockets",
    "deny-metadata-services",
    "deny-onepassword",
    "deny-privileged-mode",
    "deny-production-mcp",
    "deny-production-routes",
    "deny-provider-credentials",
    "deny-publisher-signing-overlay-install",
    "deny-secret-environment",
    "deny-ssh",
    "deny-unapproved-cordis-services",
    "enforce-dns-policy",
    "enforce-egress-policy",
    "enforce-nonroot-readonly-rootfs",
    "enforce-resource-budgets",
    "separate-candidate-controller-evaluator",
    "verify-image-signature",
)
SUPPORTED_RECORD_KINDS = frozenset(
    {
        "AgentConstitution",
        "AgentEpisode",
        "AgentHandoff",
        "AgentIdentityDescriptor",
        "AgentIdentityRevision",
        "CapabilityCandidate",
        "CapabilityEvaluation",
        "CapabilityGap",
        "CapabilityInvocation",
        "CapabilityLease",
        "CapabilityPromotion",
        "CapabilityRevocation",
        "FoundryAdmissionAttestation",
        "KnowledgeClaim",
        "ReasoningLease",
        "RuntimeAttestation",
    }
)

JSONValue: TypeAlias = None | bool | int | str | list["JSONValue"] | dict[str, "JSONValue"]
Validator: TypeAlias = Callable[[object, str], JSONValue]
FieldSpec: TypeAlias = tuple[str, Validator]


class AuditProjectionError(ValueError):
    """Raised when a projection or its pinned provenance is not closed and valid."""


def _fail(path: str, message: str) -> AuditProjectionError:
    return AuditProjectionError(f"{path}: {message}")


def _json_value(value: object, path: str) -> JSONValue:
    if value is None or isinstance(value, (str, bool)):
        return value
    if isinstance(value, int):
        if not -JSON_SAFE_INTEGER_MAX <= value <= JSON_SAFE_INTEGER_MAX:
            raise _fail(path, "integer exceeds the JSON safe range")
        return value
    if isinstance(value, float):
        raise _fail(path, "floating-point values are not canonical")
    if isinstance(value, list):
        return [_json_value(item, f"{path}[{index}]") for index, item in enumerate(value)]
    if isinstance(value, Mapping):
        result: dict[str, JSONValue] = {}
        for key, item in value.items():
            if not isinstance(key, str):
                raise _fail(path, "JSON object keys must be strings")
            result[key] = _json_value(item, f"{path}.{key}")
        return result
    raise _fail(path, f"unsupported JSON value {type(value).__name__}")


def canonical_json_bytes(value: object) -> bytes:
    """Return path-independent canonical bytes for the steward JSON domain."""

    normalized = _json_value(value, "$")
    return json.dumps(
        normalized,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def canonical_digest(value: object) -> str:
    return "sha256:" + hashlib.sha256(canonical_json_bytes(value)).hexdigest()


def _strict_json_pairs(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise AuditProjectionError(f"duplicate JSON object key: {key}")
        result[key] = value
    return result


def load_json_strict(payload: bytes) -> JSONValue:
    """Parse UTF-8 JSON while rejecting duplicates and noncanonical numbers."""

    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise AuditProjectionError("JSON payload is not UTF-8") from exc
    try:
        value = json.loads(text, object_pairs_hook=_strict_json_pairs)
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise AuditProjectionError(f"invalid JSON: {exc}") from exc
    return _json_value(value, "$")


def _closed_object(value: object, path: str, fields: tuple[FieldSpec, ...]) -> dict[str, JSONValue]:
    if not isinstance(value, Mapping):
        raise _fail(path, "expected object")
    if any(not isinstance(key, str) for key in value):
        raise _fail(path, "object keys must be strings")
    expected = {name for name, _ in fields}
    actual = set(cast(Mapping[str, object], value))
    unknown = sorted(actual - expected)
    missing = sorted(expected - actual)
    if unknown:
        raise _fail(path, f"unknown fields: {', '.join(unknown)}")
    if missing:
        raise _fail(path, f"missing fields: {', '.join(missing)}")
    source = cast(Mapping[str, object], value)
    return {name: validator(source[name], f"{path}.{name}") for name, validator in fields}


def _string(value: object, path: str) -> str:
    if not isinstance(value, str):
        raise _fail(path, "expected string")
    return value


def _bounded_string(value: object, path: str) -> str:
    result = _string(value, path)
    if not 1 <= len(result) <= 4096:
        raise _fail(path, "string length must be 1..4096")
    return result


def _identifier(value: object, path: str) -> str:
    result = _string(value, path)
    if len(result) > 200 or IDENTIFIER_RE.fullmatch(result) is None:
        raise _fail(path, "expected a lowercase steward identifier")
    return result


def _uuid(value: object, path: str) -> str:
    result = _string(value, path)
    if UUID_RE.fullmatch(result) is None:
        raise _fail(path, "expected canonical lowercase UUID")
    return result


def _digest(value: object, path: str) -> str:
    result = _string(value, path)
    if DIGEST_RE.fullmatch(result) is None:
        raise _fail(path, "expected lowercase sha256 digest")
    return result


def _timestamp(value: object, path: str) -> str:
    result = _string(value, path)
    if UTC_TIMESTAMP_RE.fullmatch(result) is None:
        raise _fail(path, "expected canonical whole-second UTC timestamp")
    try:
        datetime.fromisoformat(result)
    except ValueError as exc:
        raise _fail(path, "timestamp is not a real calendar instant") from exc
    return result


def _source_revision(value: object, path: str) -> str:
    result = _string(value, path)
    if SOURCE_REVISION_RE.fullmatch(result) is None:
        raise _fail(path, "expected a 40-character lowercase source revision")
    return result


def _boolean(value: object, path: str) -> bool:
    if type(value) is not bool:
        raise _fail(path, "expected boolean")
    return cast(bool, value)


def _integer(minimum: int = 0, maximum: int = JSON_SAFE_INTEGER_MAX) -> Validator:
    def validate(value: object, path: str) -> int:
        if type(value) is not int:
            raise _fail(path, "expected integer")
        result = cast(int, value)
        if not minimum <= result <= maximum:
            raise _fail(path, f"integer must be in {minimum}..{maximum}")
        return result

    return validate


def _enum(*allowed: str) -> Validator:
    accepted = frozenset(allowed)

    def validate(value: object, path: str) -> str:
        result = _string(value, path)
        if result not in accepted:
            raise _fail(path, f"unsupported value {result!r}")
        return result

    return validate


def _const(expected: JSONValue) -> Validator:
    def validate(value: object, path: str) -> JSONValue:
        if type(value) is not type(expected) or value != expected:
            raise _fail(path, f"expected exact value {expected!r}")
        return expected

    return validate


def _nullable(validator: Validator) -> Validator:
    def validate(value: object, path: str) -> JSONValue:
        if value is None:
            return None
        return validator(value, path)

    return validate


def _array(validator: Validator, *, maximum: int = 10_000) -> Validator:
    def validate(value: object, path: str) -> list[JSONValue]:
        if not isinstance(value, list):
            raise _fail(path, "expected array")
        if len(value) > maximum:
            raise _fail(path, f"array exceeds {maximum} items")
        return [validator(item, f"{path}[{index}]") for index, item in enumerate(value)]

    return validate


def _model(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("adapter_digest", _digest),
            ("model", _identifier),
            ("provider", _identifier),
            ("version", _identifier),
        ),
    )


def _candidate_budget(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("maximum_calls", _integer(1, 1_000_000)),
            ("maximum_cost_microunits", _integer(0, 1_000_000_000_000)),
            ("maximum_tokens", _integer(0, 1_000_000_000)),
        ),
    )


def _foundry_budget(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("cpu_millis", _integer(1)),
            ("egress_bytes", _integer(0)),
            ("maximum_tokens", _integer(0, 1_000_000_000)),
            ("memory_mebibytes", _integer(1)),
            ("wall_time_seconds", _integer(1)),
        ),
    )


def _review(expected_name: str) -> Validator:
    def validate(value: object, path: str) -> dict[str, JSONValue]:
        return _closed_object(
            value,
            path,
            (
                ("evidence_hash", _digest),
                ("name", _const(expected_name)),
                ("status", _enum("passed", "failed", "ambiguous")),
            ),
        )

    return validate


def _isolation_check(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("evidence_hash", _digest),
            ("name", _enum(*FOUNDRY_ISOLATION_CHECK_NAMES)),
            ("status", _const("passed")),
        ),
    )


def _foundry_denials(value: object, path: str) -> list[JSONValue]:
    result = cast(list[JSONValue], _array(_enum(*FOUNDRY_DENIED_CAPABILITIES), maximum=7)(value, path))
    if len(result) != len(FOUNDRY_DENIED_CAPABILITIES) or set(cast(list[str], result)) != set(
        FOUNDRY_DENIED_CAPABILITIES
    ):
        raise _fail(path, "must contain every denied capability exactly once")
    return result


def _isolation_checks(value: object, path: str) -> list[JSONValue]:
    result = cast(list[JSONValue], _array(_isolation_check, maximum=len(FOUNDRY_ISOLATION_CHECK_NAMES))(value, path))
    names = [cast(dict[str, JSONValue], item)["name"] for item in result]
    if len(names) != len(FOUNDRY_ISOLATION_CHECK_NAMES) or set(names) != set(FOUNDRY_ISOLATION_CHECK_NAMES):
        raise _fail(path, "must contain every Foundry isolation check exactly once")
    return result


def _audit_record(value: object, path: str) -> dict[str, JSONValue]:
    normalized = _json_value(value, path)
    if not isinstance(normalized, dict):
        raise _fail(path, "audit record must be an object")
    for field in ("apiVersion", "kind", "record_id", "recorded_at", "hash_algorithm", "record_hash"):
        if field not in normalized:
            raise _fail(path, f"audit record is missing common field {field}")
    if normalized["apiVersion"] != API_VERSION:
        raise _fail(path, "audit record has wrong apiVersion")
    kind = _string(normalized["kind"], f"{path}.kind")
    if kind not in SUPPORTED_RECORD_KINDS:
        raise _fail(f"{path}.kind", f"unsupported steward record kind {kind!r}")
    _uuid(normalized["record_id"], f"{path}.record_id")
    _timestamp(normalized["recorded_at"], f"{path}.recorded_at")
    if normalized["hash_algorithm"] != HASH_ALGORITHM:
        raise _fail(path, "audit record has wrong hash algorithm")
    actual_hash = _digest(normalized["record_hash"], f"{path}.record_hash")
    unhashed = dict(normalized)
    unhashed.pop("record_hash")
    domain = RECORD_HASH_DOMAIN + API_VERSION.encode() + b"\x00" + kind.encode() + b"\x00"
    expected_hash = "sha256:" + hashlib.sha256(domain + canonical_json_bytes(unhashed)).hexdigest()
    if not hmac.compare_digest(actual_hash, expected_hash):
        raise _fail(f"{path}.record_hash", "does not match canonical record content")
    return normalized


def _identity_timeline_item(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("effective_at", _timestamp),
            ("event", _enum("identity-created", "identity-revision")),
            ("identity_epoch", _integer(1)),
            ("identity_id", _identifier),
            ("identity_revision", _integer(1)),
            ("record_hash", _digest),
            ("status", _enum("pending", "active", "superseded", "revoked", "retired")),
        ),
    )


def _attested_embodiment(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("attestation_hash", _digest),
            ("dynamic_cordis_allowed", _boolean),
            ("embodiment", _enum("server-sentinel", "mac-engineer", "foundry-replay")),
            ("expires_at", _timestamp),
            ("identity_id", _identifier),
            ("installation_id", _identifier),
            ("issued_at", _timestamp),
            ("model", _model),
            ("runtime_profile_id", _identifier),
            ("session_id", _uuid),
            ("state", _enum("active", "expired")),
        ),
    )
    if result["dynamic_cordis_allowed"] is True and result["embodiment"] != "foundry-replay":
        raise _fail(path, "dynamic Cordis is only valid in the isolated Foundry embodiment")
    return result


def _episode(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("embodiment", _enum("server-sentinel", "mac-engineer", "foundry-replay")),
            ("ended_at", _nullable(_timestamp)),
            ("episode_hash", _digest),
            ("episode_id", _uuid),
            ("handoff_id", _nullable(_uuid)),
            ("identity_id", _identifier),
            ("model", _model),
            ("parent_episode_id", _nullable(_uuid)),
            ("scope_id", _identifier),
            ("started_at", _timestamp),
            (
                "state",
                _enum(
                    "open",
                    "completed",
                    "handed_off",
                    "rejected",
                    "expired",
                    "investigation_artifact",
                    "draft_pr_request",
                ),
            ),
        ),
    )
    if result["state"] == "open" and result["ended_at"] is not None:
        raise _fail(path, "open episode cannot have ended_at")
    if result["state"] != "open" and result["ended_at"] is None:
        raise _fail(path, "terminal episode requires ended_at")
    return result


def _handoff(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("expires_at", _timestamp),
            ("handoff_hash", _digest),
            ("handoff_id", _uuid),
            ("issued_at", _timestamp),
            ("source_episode_id", _uuid),
            ("state", _enum("pending", "accepted", "rejected", "expired")),
            ("target_embodiment", _enum("server-sentinel", "mac-engineer")),
            ("target_episode_id", _nullable(_uuid)),
            ("target_installation_id", _identifier),
        ),
    )
    if result["state"] == "accepted" and result["target_episode_id"] is None:
        raise _fail(path, "accepted handoff requires a target episode")
    return result


def _claim_support(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("claim_hash", _digest),
            ("claim_id", _uuid),
            (
                "knowledge_state",
                _enum("observed", "inferred", "proposed", "accepted", "superseded", "revoked"),
            ),
            ("predicate", _identifier),
            ("source_episode_id", _uuid),
            ("subject", _bounded_string),
            ("support_state", _enum(*CLAIM_SUPPORT_STATES)),
            ("supported_until", _nullable(_timestamp)),
        ),
    )
    knowledge_state = result["knowledge_state"]
    support_state = result["support_state"]
    if knowledge_state == "revoked" and support_state != "revoked":
        raise _fail(path, "revoked knowledge must project as revoked support")
    if knowledge_state == "superseded" and support_state != "superseded":
        raise _fail(path, "superseded knowledge must project as superseded support")
    if knowledge_state in {"observed", "inferred", "proposed"} and support_state != "unsupported":
        raise _fail(path, "unaccepted knowledge must project as unsupported")
    if knowledge_state == "accepted" and support_state not in {"supported", "stale", "conflicted", "unsupported"}:
        raise _fail(path, "accepted knowledge has an impossible support state")
    return result


def _reasoning_lease(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("embodiment", _enum("server-sentinel", "mac-engineer", "foundry-replay")),
            ("expected_previous_generation", _integer(0)),
            ("expires_at", _timestamp),
            ("generation", _integer(1)),
            ("issued_at", _timestamp),
            ("lease_hash", _digest),
            ("lease_id", _uuid),
            ("owner_episode_id", _uuid),
            ("scope_id", _identifier),
            ("state", _enum("active", "released", "revoked", "expired")),
        ),
    )
    if cast(int, result["generation"]) != cast(int, result["expected_previous_generation"]) + 1:
        raise _fail(path, "reasoning lease generation must advance the CAS predecessor by one")
    return result


def _capability_lease(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("audience", _identifier),
            ("capability_id", _identifier),
            ("expires_at", _timestamp),
            ("issued_at", _timestamp),
            ("lease_hash", _digest),
            ("lease_id", _uuid),
            ("mode", _enum("read", "intent")),
            ("permitted_interface", _identifier),
            ("state", _enum("active", "revoked", "expired")),
        ),
    )


def _capability_gap(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("closed_at", _nullable(_timestamp)),
            ("gap_hash", _digest),
            ("gap_id", _uuid),
            ("required_interface", _identifier),
            ("source_episode_id", _uuid),
            ("status", _enum("open", "closed", "superseded", "revoked")),
        ),
    )
    if result["status"] == "open" and result["closed_at"] is not None:
        raise _fail(path, "open gap cannot have closed_at")
    if result["status"] != "open" and result["closed_at"] is None:
        raise _fail(path, "terminal gap requires closed_at")
    return result


def _foundry_admission(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("admission_hash", _digest),
            ("admission_id", _uuid),
            ("admitted", _const(True)),
            ("budget", _foundry_budget),
            ("credential_access", _const(False)),
            ("denied_capabilities", _foundry_denials),
            ("dependency_lock_digest", _digest),
            ("expires_at", _timestamp),
            ("fixture_bundle_digest", _digest),
            ("image_digest", _digest),
            ("installation_id", _identifier),
            ("isolation_checks", _isolation_checks),
            ("issued_at", _timestamp),
            ("job_id", _uuid),
            ("network_policy_digest", _digest),
            ("production_network_access", _const(False)),
            ("sbom_digest", _digest),
            ("source_archive_digest", _digest),
            ("source_revision", _source_revision),
            ("state", _enum("active", "expired")),
            ("wipe_policy", _const("destroy-after-one-job")),
        ),
    )
    return result


def _capability_candidate(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("adversarial_review", _review("adversarial-review")),
            ("budget", _candidate_budget),
            ("candidate_hash", _digest),
            ("candidate_id", _uuid),
            ("closed_gap_hash", _digest),
            ("code_digest", _digest),
            ("dependency_lock_digest", _digest),
            ("foundry_admission_hash", _digest),
            ("identity_id", _identifier),
            ("interface_schema_digest", _digest),
            ("model", _model),
            ("reviewer", _identifier),
            ("reviewer_key_id", _identifier),
            ("self_install_allowed", _const(False)),
            ("self_promotion_allowed", _const(False)),
            ("signature_bundle_hash", _digest),
            ("source_digest", _digest),
            ("source_revision", _source_revision),
            ("static_review", _review("static-review")),
            ("status", _enum("draft", "evaluated", "rejected", "superseded")),
            ("tool_profile_digest", _digest),
        ),
    )


def _capability_evaluation(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("candidate_hash", _digest),
            ("credentials_accessed", _const(False)),
            ("evaluation_hash", _digest),
            ("evaluation_id", _uuid),
            ("evaluator_attestation_hash", _digest),
            ("outcome", _enum("passed", "failed", "ambiguous")),
            ("production_accessed", _const(False)),
            ("terminal_artifact", _enum("investigation_artifact", "draft_promotion_artifact")),
        ),
    )
    expected = "draft_promotion_artifact" if result["outcome"] == "passed" else "investigation_artifact"
    if result["terminal_artifact"] != expected:
        raise _fail(path, f"{result['outcome']} evaluation requires {expected}")
    return result


def _capability_promotion(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("evaluation_hash", _digest),
            ("human_decision", _enum("pending", "approved", "rejected")),
            ("may_deploy", _const(False)),
            ("may_install", _const(False)),
            ("may_merge", _const(False)),
            ("may_publish", _const(False)),
            ("overlay_selection_present", _boolean),
            ("permitted_action", _enum("investigation_artifact", "draft_pr_request")),
            ("promotion_hash", _digest),
            ("promotion_id", _uuid),
            ("signed_release_present", _boolean),
            ("status", _enum("draft", "review_requested", "approved_for_release", "rejected")),
        ),
    )
    if result["status"] == "approved_for_release" and (
        result["human_decision"] != "approved"
        or result["signed_release_present"] is not True
        or result["overlay_selection_present"] is not True
        or result["permitted_action"] != "draft_pr_request"
    ):
        raise _fail(path, "approved release requires exact human approval, signed release, and overlay selection")
    return result


def _capability_revocation(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("capability_id", _identifier),
            ("effective_at", _timestamp),
            ("provider_rejection_required", _const(True)),
            ("reactive_profile_state", _const("deactivated")),
            ("revocation_hash", _digest),
            ("revocation_id", _identifier),
            ("target_revocation_identity", _identifier),
        ),
    )


def _capability_invocation(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("call_index", _integer(1)),
            ("capability_id", _identifier),
            ("completed_at", _timestamp),
            ("disposition", _enum("succeeded", "rejected", "expired", "revoked")),
            ("entry_validation", _enum("accepted", "rejected")),
            ("invocation_hash", _digest),
            ("invocation_id", _uuid),
            ("return_validation", _nullable(_enum("accepted", "rejected"))),
            ("started_at", _timestamp),
        ),
    )
    if result["disposition"] == "succeeded" and (
        result["entry_validation"] != "accepted" or result["return_validation"] != "accepted"
    ):
        raise _fail(path, "successful invocation requires provider validation at entry and return")
    if result["return_validation"] is not None and result["entry_validation"] != "accepted":
        raise _fail(path, "return validation is impossible after rejected entry validation")
    return result


WARNING_RULES: dict[str, tuple[str, str]] = {
    "stale-knowledge-claim": ("stale", "KnowledgeClaim"),
    "conflicted-knowledge-claim": ("conflicted", "KnowledgeClaim"),
    "revoked-knowledge-claim": ("revoked", "KnowledgeClaim"),
    "unsupported-knowledge-claim": ("unsupported", "KnowledgeClaim"),
    "revoked-capability-lease": ("revoked", "CapabilityLease"),
    "pending-capability-gap": ("pending", "CapabilityGap"),
    "pending-capability-promotion": ("pending", "CapabilityPromotion"),
}


def _warning(value: object, path: str) -> dict[str, JSONValue]:
    result = _closed_object(
        value,
        path,
        (
            ("category", _enum(*WARNING_CATEGORIES)),
            ("code", _enum(*WARNING_RULES)),
            ("source_id", _bounded_string),
            ("source_kind", _enum("KnowledgeClaim", "CapabilityLease", "CapabilityGap", "CapabilityPromotion")),
            ("source_record_hash", _digest),
        ),
    )
    expected_category, expected_kind = WARNING_RULES[cast(str, result["code"])]
    if result["category"] != expected_category or result["source_kind"] != expected_kind:
        raise _fail(path, "warning category and source kind do not match its closed code")
    return result


def _vocabulary(value: object, path: str) -> dict[str, JSONValue]:
    return _closed_object(
        value,
        path,
        (
            ("claim_support_states", _const(list(CLAIM_SUPPORT_STATES))),
            ("record_selection", _const("latest-revision-per-logical-id-then-record-hash")),
            ("time_basis", _const("fixed-as-of-inclusive-utc")),
            ("warning_categories", _const(list(WARNING_CATEGORIES))),
        ),
    )


PROJECTION_FIELDS: tuple[FieldSpec, ...] = (
    ("attested_embodiments", _array(_attested_embodiment)),
    ("capability_candidates", _array(_capability_candidate)),
    ("capability_evaluations", _array(_capability_evaluation)),
    ("capability_gaps", _array(_capability_gap)),
    ("capability_invocations", _array(_capability_invocation)),
    ("capability_leases", _array(_capability_lease)),
    ("capability_promotions", _array(_capability_promotion)),
    ("capability_revocations", _array(_capability_revocation)),
    ("claim_support_states", _array(_claim_support)),
    ("episodes", _array(_episode)),
    ("foundry_admissions", _array(_foundry_admission)),
    ("handoffs", _array(_handoff)),
    ("identity_timeline", _array(_identity_timeline_item)),
    ("reasoning_leases", _array(_reasoning_lease)),
    ("vocabulary", _vocabulary),
    ("warnings", _array(_warning)),
)


def normalize_expected_projection(value: object, path: str = "$.expected_projection") -> dict[str, JSONValue]:
    """Validate every closed v1 projection section and return a detached copy."""

    return _closed_object(value, path, PROJECTION_FIELDS)


def validate_audit_projection_document(value: object) -> dict[str, JSONValue]:
    """Validate a public projection document without interpreting it as authority."""

    document = _closed_object(
        value,
        "$",
        (
            ("apiVersion", _const(API_VERSION)),
            ("as_of", _timestamp),
            ("authority_effect", _const("none")),
            ("contains_private_identity", _const(False)),
            ("expected_projection", normalize_expected_projection),
            ("expected_projection_digest", _digest),
            ("kind", _const(AUDIT_VECTOR_KIND)),
            ("records", _array(_audit_record)),
            ("records_digest", _digest),
            ("synthetic", _const(True)),
        ),
    )
    expected_projection = cast(dict[str, JSONValue], document["expected_projection"])
    expected_digest = canonical_digest(expected_projection)
    if not hmac.compare_digest(cast(str, document["expected_projection_digest"]), expected_digest):
        raise _fail("$.expected_projection_digest", "does not bind the normalized projection")
    records = cast(list[JSONValue], document["records"])
    records_digest = canonical_digest(records)
    if not hmac.compare_digest(cast(str, document["records_digest"]), records_digest):
        raise _fail("$.records_digest", "does not bind the record array")
    canonical_as_of = cast(str, document["as_of"])
    record_ids: set[str] = set()
    record_hashes: set[str] = set()
    for index, item in enumerate(records):
        record = cast(dict[str, JSONValue], item)
        if cast(str, record["recorded_at"]) > canonical_as_of:
            raise _fail(f"$.records[{index}].recorded_at", "future record leaked into fixed as_of projection")
        record_id = cast(str, record["record_id"])
        record_hash = cast(str, record["record_hash"])
        if record_id in record_ids or record_hash in record_hashes:
            raise _fail(f"$.records[{index}]", "duplicate record identity or hash")
        record_ids.add(record_id)
        record_hashes.add(record_hash)
    for index, item in enumerate(cast(list[JSONValue], expected_projection["attested_embodiments"])):
        attestation = cast(dict[str, JSONValue], item)
        expected_state = "active" if canonical_as_of < cast(str, attestation["expires_at"]) else "expired"
        if attestation["state"] != expected_state:
            raise _fail(f"$.expected_projection.attested_embodiments[{index}].state", "does not match as_of")
    for index, item in enumerate(cast(list[JSONValue], expected_projection["foundry_admissions"])):
        admission = cast(dict[str, JSONValue], item)
        expected_state = "active" if canonical_as_of < cast(str, admission["expires_at"]) else "expired"
        if admission["state"] != expected_state:
            raise _fail(f"$.expected_projection.foundry_admissions[{index}].state", "does not match as_of")
    return document


PINNED_SOURCE_LOCK: dict[str, JSONValue] = {
    "canonical_commit": PINNED_CANONICAL_COMMIT,
    "canonical_generator": {
        "path": "ops/steward/contracts/steward_v1.py",
        "sha256": PINNED_GENERATOR_SHA256,
    },
    "canonical_repository": "https://github.com/masonjames/platform-infra",
    "generated_directory": "contracts/platform-steward/v1",
    "generated_file_count": 19,
    "schema_manifest": {
        "path": "contracts/platform-steward/v1/schema-manifest.json",
        "sha256": PINNED_SCHEMA_MANIFEST_SHA256,
    },
    "source_lock_version": 1,
    "test_vectors": {
        "audit_projection": {
            "path": "contracts/platform-steward/v1/test-vectors/audit-projection-records.json",
            "sha256": PINNED_AUDIT_VECTOR_SHA256,
        },
        "canonical_hash": {
            "path": "contracts/platform-steward/v1/test-vectors/canonical-hash-vectors.json",
            "sha256": PINNED_CANONICAL_HASH_VECTOR_SHA256,
        },
    },
}


def _file_digest(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _assert_file_digest(path: Path, expected: str) -> None:
    try:
        actual = _file_digest(path)
    except OSError as exc:
        raise AuditProjectionError(f"cannot read pinned contract file {path}: {exc}") from exc
    if not hmac.compare_digest(actual, expected):
        raise AuditProjectionError(f"pinned contract digest mismatch for {path}: {actual}")


def _validate_source_lock(value: object) -> None:
    normalized = _json_value(value, "$")
    if normalized != PINNED_SOURCE_LOCK:
        raise AuditProjectionError("SOURCE.lock.json does not match the compiled closed source lock")


def load_pinned_audit_projection(repository_root: Path | None = None) -> dict[str, JSONValue]:
    """Verify the complete generated mirror and load its read-only projection.

    No caller-selected hash or source revision is accepted.  The function reads
    only the checked-in lock, manifest, generated schemas, and public vector.
    """

    root = repository_root or Path(__file__).resolve().parents[1]
    contract_root = root / "contracts" / "platform-steward"
    lock_path = contract_root / "SOURCE.lock.json"
    if contract_root.is_symlink() or lock_path.is_symlink():
        raise AuditProjectionError("pinned contract root and source lock cannot be symlinks")
    try:
        source_lock = load_json_strict(lock_path.read_bytes())
    except OSError as exc:
        raise AuditProjectionError(f"cannot read pinned source lock {lock_path}: {exc}") from exc
    _validate_source_lock(source_lock)

    generated_root = contract_root / "v1"
    manifest_path = generated_root / "schema-manifest.json"
    if generated_root.is_symlink() or manifest_path.is_symlink():
        raise AuditProjectionError("generated contract root and manifest cannot be symlinks")
    _assert_file_digest(manifest_path, PINNED_SCHEMA_MANIFEST_SHA256)
    manifest_value = load_json_strict(manifest_path.read_bytes())
    if not isinstance(manifest_value, dict):
        raise AuditProjectionError("schema manifest must be an object")
    expected_manifest_keys = {
        "apiVersion",
        "canonical_source",
        "canonical_source_sha256",
        "kind",
        "schema_dialect",
        "schemas",
        "test_vectors",
    }
    if set(manifest_value) != expected_manifest_keys:
        raise AuditProjectionError("schema manifest is not the closed v1 shape")
    if manifest_value["apiVersion"] != API_VERSION:
        raise AuditProjectionError("schema manifest has wrong apiVersion")
    if manifest_value["canonical_source"] != "ops/steward/contracts/steward_v1.py":
        raise AuditProjectionError("schema manifest has wrong canonical generator path")
    if manifest_value["canonical_source_sha256"] != PINNED_GENERATOR_SHA256:
        raise AuditProjectionError("schema manifest has wrong canonical generator digest")
    if manifest_value["kind"] != "PlatformStewardSchemaManifest":
        raise AuditProjectionError("schema manifest has wrong kind")
    if manifest_value["schema_dialect"] != "https://json-schema.org/draft/2020-12/schema":
        raise AuditProjectionError("schema manifest has wrong dialect")

    schemas = manifest_value["schemas"]
    test_vectors = manifest_value["test_vectors"]
    if not isinstance(schemas, dict) or len(schemas) != 16:
        raise AuditProjectionError("schema manifest must list exactly 16 schemas")
    if not isinstance(test_vectors, dict) or set(test_vectors) != {
        "test-vectors/audit-projection-records.json",
        "test-vectors/canonical-hash-vectors.json",
    }:
        raise AuditProjectionError("schema manifest has the wrong test-vector set")

    expected_relative_files = {Path("schema-manifest.json")}
    for filename, digest in {**schemas, **test_vectors}.items():
        if not isinstance(filename, str) or Path(filename).is_absolute() or ".." in Path(filename).parts:
            raise AuditProjectionError("schema manifest contains an unsafe relative path")
        if not isinstance(digest, str) or DIGEST_RE.fullmatch(digest) is None:
            raise AuditProjectionError(f"schema manifest has invalid digest for {filename}")
        relative = Path(filename)
        expected_relative_files.add(relative)
        path = generated_root / relative
        if path.is_symlink():
            raise AuditProjectionError(f"generated contract mirror cannot contain symlink {relative}")
        _assert_file_digest(path, digest)

    actual_relative_files: set[Path] = set()
    for path in generated_root.rglob("*"):
        if path.is_symlink():
            raise AuditProjectionError(f"generated contract mirror cannot contain symlink {path}")
        if path.is_file():
            actual_relative_files.add(path.relative_to(generated_root))
    if actual_relative_files != expected_relative_files or len(actual_relative_files) != 19:
        raise AuditProjectionError("generated contract mirror contains missing or unexpected files")

    audit_vector_path = generated_root / "test-vectors" / "audit-projection-records.json"
    _assert_file_digest(audit_vector_path, PINNED_AUDIT_VECTOR_SHA256)
    return validate_audit_projection_document(load_json_strict(audit_vector_path.read_bytes()))
